### ISSUE TITLE
:sparkles: **MVP Checklist** :sparkles:

### ISSUE THREAD

**Issue by ConnorSullivan10** [ConnorSullivan10/InsideIntervals#4]
- [ ] Front-End: 
- [ ] Back-End: 
- [ ] Database: #3

Goals:
- [ ] Goal 1: Create a page featuring interactive tablature, musical examples, video examples, and explanations of each of the 12 intervals.
- [ ] Goal 2: Create a feature where users can import their own tabs via an input to JSON converter which then uses the imported Javascript package above to analyze the tab, and give examples of what intervals are used.
- [ ] Goal 3: Users who import their tabs can also get chord suggestions that align with their tabs, as well as suggestions of what other chords would work well in their musical composition.

Stretch Goals:
- [ ] Stretch Goal 1: Include some sort of midi player, where users can play notes on an interactive keyboard/guitar fretboard of some sort while on the application. Still researching best ideas of how this would work on the front end.
- [ ] Stretch Goal 2: Allow feature to upload tabs for different stringed instruments
